# AlphaDev casinomex database
services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: timba2024root
      MARIADB_PASSWORD: timba2024
      MARIADB_USER: timbadb
      MARIADB_DATABASE: timba-data-base
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - type: bind
        source: ./backup/timba-backup-2024-04-09.sql
        target: /docker-entrypoint-initdb.d/backup.sql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  myapp:

