# AlphaDev casinomex database
services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: timba2024root
      MARIADB_USER: timba
      MARIADB_PASSWORD: timba2024
      MARIADB_DATABASE: timba-dev
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
