version: '3.1'

# AlphaDev casinomex database
services:
  casinomex_db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: timba2024
      MYSQL_DATABASE: timba-data-base
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3307:3306

  casinomex_adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

